app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Authentication routes...
Route::get('/', ['as' =>'login', 'uses' => 'Auth\AuthController@getLogin']);
Route::get('auth/login', ['as' =>'login', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login', ['as' =>'login', 'uses' => 'Auth\AuthController@postLogin']);
Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@getLogout']);


Route::group(['middleware' => ['auth', 'cors']], function()
{

	Route::get('home', ['as' => 'home', 'uses' => 'HomeController@index']);
	
	// Registration routes...
	Route::get('usuarios/tag', ['as' => 'usuarios.tag', 'uses' => 'Auth\AuthController@tag']);
	Route::get('usuarios/{id}/tagselecionadas', ['as' => 'usuarios.tagselecionadas', 'uses' => 'Auth\AuthController@tagselecionadas']);
	
	// Password reset link request routes...
	Route::get('forgot', ['as' =>'password/email', 'uses' => 'Auth\PasswordController@getEmail']);
	Route::post('forgot', ['as' =>'password/email', 'uses' => 'Auth\PasswordController@postEmail']);


	// Password reset routes...
	Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
	Route::post('password/reset', 'Auth\PasswordController@postReset');

	// Projetos
	Route::get('projeto/tag', ['as' => 'projeto.tag', 'uses' => 'ProjetosController@tag']);
	Route::get('projeto/{id}/tagselecionadas', ['as' => 'projeto.tagselecionadas', 'uses' => 'ProjetosController@tagselecionadas']);
	Route::get('projeto/{id}/tagtelefones', ['as' => 'projeto.tagselecionadas', 'uses' => 'ProjetosController@tagtelefones']);
	Route::get('projeto/{id}/datatable', ['as' =>'projeto.dados', 'uses' => 'ProjetosController@dados']);


	// Verifica se e admin se for tem acesso ao projetos e usuarios
	Route::group(['middleware' => ['admin']], function()
	{
		Route::resource('projetos', 'ProjetosController');
		Route::resource('usuarios', 'Auth\AuthController');

	});

	Route::group(['middleware' => ['userProject']], function()
	{
	
	// Cadastros
	Route::get('projetos/{id}/cadastros', ['as' => 'cadastros.index', 'uses' => 'CadastrosController@index']);
	Route::get('cadastros/{id}/destroy', ['as' => 'cadastros.destroy', 'uses' => 'CadastrosController@destroy']);
	Route::get('cadastros/{id}/datatable', ['as' => 'cadastros.dados', 'uses' => 'CadastrosController@dados']);
	Route::post('cadastros/{id}/excel', ['as' =>'cadastros.excel', 'uses' => 'CadastrosController@excel']);

	// Estatisticas
	Route::get('projetos/{id}/estatisticas', ['as' => 'estatisticas.index', 'uses' => 'EstatisticasController@index']);
	Route::get('estatisticas/{id}', ['as' => 'estatisticas.dados', 'uses' => 'EstatisticasController@dados']);
	Route::get('estatisticas/{id}/datatable', ['as' => 'estatisticas.datatable', 'uses' => 'EstatisticasController@datatable']);

	// Calltracker
	Route::get('projetos/{id}/calltracker', ['as' =>'calltracker.index', 'uses' => 'CalltrackerController@index']);
	Route::get('calltracker/{id}/destroy', ['as' => 'calltracker.destroy', 'uses' => 'CalltrackerController@destroy']);
	Route::get('calltracker/{id}/datatable', ['as' =>'calltracker.dados', 'uses' => 'CalltrackerController@dados']);
	Route::post('calltracker/{id}/audio', ['as' =>'calltracker.audio', 'uses' => 'CalltrackerController@audio']);
	Route::post('calltracker/{id}/excel',  ['as' =>'calltracker.excel', 'uses' => 'CalltrackerController@excel']);

	// Leads
	Route::get('projetos/{id}/leads', ['as' => 'leads.index', 'uses' => 'LeadsController@index']);
	Route::get('projetos/{pro_id}/leads/{id}', ['as' => 'leads.edit', 'uses' => 'LeadsController@edit']);
	Route::patch('projetos/{pro_id}/leads/{id}/', ['as' =>'leads.update', 'uses' => 'LeadsController@update']);
	Route::delete('projetos/{id}/leads', ['as' => 'leads.destroy', 'uses' => 'LeadsController@destroy']);
	Route::post('leads', ['as' =>'leads.excel', 'uses' => 'LeadsController@excel']);

	});
});

Route::group(array('prefix' => 'api'), function()
{

  Route::get('/', function () {
      return response()->json(['message' => 'Jobs API', 'status' => 'Connected']);;
  });

  Route::resource('leads', 'Api\LeadsController');
});

resources/views/ api.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
    <input name="nome" type="text" value="renato">
    <input name="email" type="text" value="rspindola@email.com">
    <input name="telefone" type="text" value="21945384349">
    <input name="mensagem" type="text" value="teste">
    <input name="coords" type="text" value="3920392">
    <input name="origem" type="text" value="renato">
    <input name="peca" type="text" value="renato">
    <input name="term" type="text" value="renato">
    <input name="data" type="text" value="18/06/2019">
    <input name="sistema" type="text" value="chrome">
    <input name="pro_id" type="text" value="renato">
    <input name="res_id" type="text" value="renato">
    </form>

    <script>
    var formData = {
        'nome': $('input[name=nome-1]').val(),
        'telefone': $('input[name=telefone-1]').val(),
        'email': $('input[name=email-1]').val(),
        'mensagem': $('textarea[name=mensagem-1]').val(),
        'honeypot': $('input[name=honeypot-1]').val(),
        };
        $.ajax({
                type: 'POST',
                url: 'http://thebox.sensorialbr.com/api/leads',
                data: formData,
                dataType: 'json',
                encode: true
            })
            .done(function (data) {
                    console.log(formData);
                } else {
                    console.log(formData);
                }
            };
    </script>
</body>
</html>

resources/views/home.blade.php
@extends('layout')
@section('content')



            <div class="sub-header">
                <div class="row">
                    <div class="col-sm-7 col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="#">Dashboard</a></li>
                        </ol>
                    </div>
                    <div class="col-sm-5 col-xs-12">
                        <!-- <div class="datePicker">
                            <div id="reportrange">
                                <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;
                                <span></span> <b class="caret"></b>
                            </div>
                        </div> -->
                    </div>
                </div>
            </div>


            <?php $cores = array('azul', 'roxo', 'rose', 'amarelo', 'azul', 'roxo', 'rose', 'amarelo'); $i =0; ?>


            <div class="container-fluid dash-content">
                <div class="row">
                    <div class="col-lg-12 margem-topo">
                        <div class="panel panel-inside">
                            <div class="panel-body">
                                <div class="panel-heading">Projetos</div>
                                <hr>
                                <div class="row">

                                @foreach ($Dados as $row)
                                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                                        <a href="{{ route('estatisticas.index', ['id' => $row->id ]) }}" class="card margem-bottom-2x {!! $cores[$i] !!}">
                                            {!! $row->projeto !!}
                                            <?php if($i == 7) $i = 0; else $i++ ?>
                                        </a>
                                    </div>
                                @endforeach
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Dashboard Sensorial</title>

    <link href="{{ asset('assets/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/font-awesome-4.3.0/css/font-awesome.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('assets/bootstraoTagsInput/bootstrap-tagsinput.css') }}">

    <link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.css">
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/responsive/1.0.7/css/responsive.dataTables.min.css">
    <link href="http://cdnjs.cloudflare.com/ajax/libs/remodal/1.0.7/remodal.css" rel="stylesheet"/>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/remodal/1.0.7/remodal-default-theme.min.css" rel="stylesheet"/>

    {!! Html::style('css/app.css') !!}
</head>
<body class="contract">
    <div class="wrapper remodal-bg">
        <nav id="sidebar" role="navigation" -step="2" data-intro="Template has <b>many navigation styles</b>" data-position="right" class="navbar-default navbar-static-side" style="min-height: 100%;">
            <div class="sidebar-collapse menu-scroll" style="overflow: hidden;">
                <ul class="nav side-menu">
                    <!-- Logotipo -->
                    <li class="active logotipo">
                        <a href="{{ route('home')}}">
                            <h1 class="brand">
                                Sensorial
                            </h1>
                        </a>
                    </li>
                    <!-- Itens menu -->
                    <li>
                        <a href="{{ route('home')}}">
                            <i class="fa fa-tachometer"></i>
                            <span class="menu-title">Dashboard</span>
                        </a>
                    </li>

                    @if(Auth::user()->isAdmin())
                    <!-- Usuários -->
                    <li>
                        <a href="{{ action('Auth\AuthController@index')}}">
                            <i class="fa fa-users"></i>
                            <span class="menu-title">Usuários</span>
                        </a>
                    </li>

                    <!-- Usuários -->
                    <li>
                        <a href="{{ action('ProjetosController@index')}}">
                            <i class="fa fa-list-alt"></i>
                            <span class="menu-title">Administrar projetos</span>
                        </a>
                    </li>
                    @endif
                    @if($Menu)
                    @foreach ($Menu as $row)

                    <li>
                        <a href="#" class="sub">
                            <i class="fa fa-th-list"></i>
                            <span class="menu-title">{{ $row->projeto }}</span>
                        </a>
                        <ul>
                            <li><a href="{{ route('estatisticas.index', ['id' => $row->id ]) }}">
                                <i class="fa fa-line-chart"></i>
                                <span class="menu-title">Estatísticas</span>
                            </a></li>
                            <li><a href="{{ route('cadastros.index', ['id' => $row->id ]) }}">
                                <i class="fa fa-users"></i>
                                <span class="menu-title">Cadastros</span>
                            </a></li>

                            <li><a href="{{ route('calltracker.index',  ['id' => $row->id ]) }}">
                                <i class="fa fa-phone"></i>
                                <span class="menu-title">Call Tracker</span>
                            </a></li>

                            <li><a href="{{ route('leads.index',  ['id' => $row->id ]) }}">
                               <i class="fa fa-bar-chart" aria-hidden="true"></i>
                                <span class="menu-title">Leads</span>
                            </a></li>

                        </ul>
                    </li>

                    @endforeach
                    @endif

                    <li>
                        <a href="{{ route('logout') }}">
                            <i class="fa fa-power-off"></i>
                            <span class="menu-title">Sair</span>
                        </a>
                    </li>

                </ul>
            </div>
        </nav>

        <div id="page-wrapper" class="content">
            <nav class="navbar navbar-top container-fluid">
                <div id="navbar" class="navbar-collapse collapse">

                  
                    <ul class="nav navbar-nav navbar-left">
                        <li><a id="menu-toggle" href="#"><i class="fa fa-bars"></i></a></li>
                          @if(Auth::user()->isAdmin())
                        <li class="hidden-xs"><a href="{{ route('projetos.create') }}"><i class="fa fa-plus"></i> Adicionar projeto</a></li>
                        <li class="hidden-xs"><a href="{{ route('usuarios.create') }}"><i class="fa fa-user-plus"></i> Adicionar usuário</a></li>
                          @endif
                    </ul>
                  

                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <div class="user">
                                    <img src="{{ url('/') }}/img/Avatar/{{ Auth::user()->email }}" height="29" width="29">
                                    {{ Auth::user()->name }}<span class="caret"></span>
                                </div>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <!-- <li><a href="#"><i class="fa fa-user"></i>Minha Conta</a></li>
                                <li><a href="#"><i class="fa fa-envelope"></i>Mensagens</a></li>
                                <li class="divider"></li> -->
                                <li><a href="{{ route('logout') }}"><i class="fa fa-power-off"></i>Sair</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
            <script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>
            @yield('content')
        </div>
    </div>


    <script src="{{ asset('assets/bootstrap/js/bootstrap.min.js')}}"></script>
    <script src="{{ asset('assets/bootstraoTagsInput/bootstrap-tagsinput.min.js')}}"></script>

    <script src="http://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>
    <script src="http://cdn.datatables.net/1.10.11/js/dataTables.bootstrap.min.js"></script>
    <script src="http://cdn.datatables.net/responsive/1.0.7/js/dataTables.responsive.min.js"></script>
    <script type="text/javascript" src="{{ asset('js/momentjs.js') }}"></script>
    <script type="text/javascript" src="http://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>



    <script src="http://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/remodal/1.0.7/remodal.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-maskmoney/3.0.2/jquery.maskMoney.min.js"></script>




    <script src="{{ URL::to('/') }}/js/main.js"></script>


    <!--====  End of Remodal  ====-->

    <div class="remodal" data-remodal-id="modal">
        <button data-remodal-action="close" class="remodal-close"></button>
        <h1 class="ModalTitulo">Titulo</h1>
        <p class="ModalDados">
            Dados
        </p>
        <br>
        <!-- <button data-remodal-action="cancel" class="remodal-cancel">Cancel</button> -->
        <button data-remodal-action="confirm" class="remodal-confirm">OK</button>
    </div>


    @yield('scripts')
</body>
</html>